# Generated by Django 4.0.3 on 2022-03-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
                ('manager_name', models.CharField(max_length=100)),
                ('opentime', models.TimeField()),
                ('closetime', models.TimeField()),
                ('outlet_img', models.ImageField(upload_to='pics/outlet')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_img', models.ImageField(upload_to='pics/product')),
                ('product_price', models.IntegerField()),
            ],
        ),
    ]
